### PR TITLE
Params overhaul

### PR DESCRIPTION
**Pull request by daler**
In order to support all the new track types (bigNarrowPeak, bigMaf, bigChain, bigGenePred, etc) the parameters needed fixing and generalizing so they could be more easily shared among similar types. For example, bigNarrowPeak shares many of the bigBed params, but there wasn't a good way of setting this up. Furthermore, if we keep the existing architecture, the next time there's an update it will be a lot of work to support everything.

This PR makes some substantial changes.

1. There is a new `parsed_params.py` file that now uses a `Param` object. This object now accepts a list of track types for which the parameter is valid, so we can programmatically extract parameters for a track type and store them in a dict.
2. The `track.BaseTrack` object and its subclasses now refer to lists of parameters rather than OrderedDicts. Much easier to properly and consistently sort.
3. A new `parse.py` script scrapes the HTML from https://genome.ucsc.edu/goldenpath/help/trackDb/trackDbHub.html. It transforms the various `<div>`s and `<span>`s and `<code>`s into a data structure. This script outputs text that is intended to be diffed against `parsed_params.py`

With these changes (and some supporting changes as well), `trackhub` is fully up-to-date with the specification, which includes all parameters and track types. Importantly, it is designed to be easily updated, either in bulk or incrementally, for any future changes in the track hub spec.

Other changes include better rsync+symlink support. Previously, even when using rsync with the `-L` option to follow symlinks, the modification time of the symlink is used rather than that of the target. That meant that any time the symlink is recreated rsync saw it as new and that the file needed to be transferred.  Now, specifically, on Python 3 and on filesystems that support it, the modification time of symlinks are set to the modification time of their target.

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
What is keeping this from being released?

**Comment by Maarten-vd-Sande** [comment]
@daler I have been using this branch for over a year with success. Is there any reason why you are not merging it? I developed a package which I would like to release on bioconda, but it depends on this branch specifically.

Is there a way I can help to move this forward?

**Comment by daler** [comment]
@Maarten-vd-Sande great to hear you've been using this, sorry it's been so low on my priority list. Looks like you worked out using it in bioconda. Merging this now and will be working out the kinks on master branch in prep for a new release.

**Comment by Maarten-vd-Sande** [comment]
No problem! I'm just happy that this exists :)

**Pull request merged**
